---

- hosts: all
  become: true
  tasks:

  - name: update repository index
    apt:
      update_cache: yes

  - name: installs nano
    apt:
      name: nano
      state: latest

  - name: intalls htop package
    apt:
      name: htop
      state: latest

  - name: installs cockpit
    apt:
      name: cockpit
      state: latest
