---
- name: install updates and autoremoves packages (Ubuntu, Debian)
  hosts: openmediavault:pihole
  become: True
  tasks:
  - name: upgrade with apt
    apt:
      upgrade: dist
      update_cache: yes
      autoremove: yes
      purge: yes
    when: ansible_distribution in ["Debian", "Ubuntu"]

- name: localhost
  hosts: local
  connection: local
  become: True
  gather_facts: yes
  tasks:
    - name: Full system upgrade
      community.general.pacman:
        update_cache: true
        upgrade: true

- name: "upgrade with pihole"
  become: false
  hosts: pihole
  tasks:
  - name: "Look For Pihole upgrade"
    tags: pihole,ubuntu
    register: shell_output
    shell: "pihole -up"
  -
    debug: var=shell_output.stdout_lines
