---

- hosts: pihole
  become: true
  tasks:

  - name: update repository index
    apt:
      update_cache: yes

  - name: install updates (Ubuntu, Debian) 
    apt:
      upgrade: dist
      update_cache: yes
      when: ansible_distribution in ["Ubuntu"]

- hosts: openmediavault
  become: true
  tasks:

  - name: update repository index
    apt:
      update_cache: yes

  - name: install updates (Ubuntu, Debian) 
    apt:
      upgrade: dist
      update_cache: yes
