---

- hosts: pihole
  become: true
  tasks:

  - name: update repository index
    apt:
      update_cache: yes

  - name: install updates (Ubuntu, Debian) 
    apt:
      upgrade: dist
      update_cache: yes

  - name: auto removes packages
    apt:
      autoremove: yes
      purge: yes



- 
  become: false
  hosts: "*"
  tasks: 
    - 
      name: "Look For Pihole upgrade"
      register: shell_output
      shell: "pihole -up"
    - 
      debug: var=shell_output.stdout_lines

- hosts: openmediavault
  become: true
  tasks:

  - name: update repository index
    apt:
      update_cache: yes

  - name: install updates (Ubuntu, Debian) 
    apt:
      upgrade: dist
      update_cache: yes

  - name: auto removes packages
    apt:
      autoremove: yes
      purge: yes
