---

- hosts: all
  become: true
  tasks:

  - name: install updates and autoremoves packages (Ubuntu, Debian) 
    apt:
      upgrade: dist
      update_cache: yes
      autoremove: yes
      purge: yes

- 
  become: false
  hosts: pihole
  tasks: 
    - 
      name: "Look For Pihole upgrade"
      register: shell_output
      shell: "pihole -up"
    - 
      debug: var=shell_output.stdout_lines

